### ISSUE TITLE
Change more than one image per execution

### ISSUE THREAD

**Issue by AlbertoFemenias** [prefapp/action-state-repo-update-image#84]
## Motivation
Relates to https://github.com/prefapp/action-deployment-dispatch/issues/19

Right now the action changes only one image per dispatch. We would like to remove the complexity from the code repositories.

The action should now receive an array of all the different images that relate to a repo and instead of change one image in one PR, it should evaluate which images have changed in which services and open PRs updating only those new images.

These were the old inputs:
```yaml
- name: Update image  
      uses: prefapp/action-state-repo-update-image@feature/v3
      with:
        tenant: tenant_name
        application: app1
        environment: dev
        service_names: '["api", "client"]' # string! example: ${{ toJSON(github.event.client_payload.service_names) }}
        image: image:new
        reviewers: '["juana", "suhermana"]' #OPTIONAL again JSON array 
        pr_title: PR title # will be removed
        pr_body: PR body # will be removed
        branch_name: automated/update-image #OPTIONAL
```

And this would be the new ones:
```yaml
- name: Update image  
      uses: prefapp/action-state-repo-update-image@feature/v3
      with:
        image_matrix: <json array with one entry per image> # mandatory - JSON format
```

```js
image_matrix = [ 
    {
          tenant: 'tenant1',
          app: 'release_foo',
          env: 'pre',
          service_names: [ 'hello' ],
          image: 'test-service:last_prerelease_default',
          reviewers: [ 'test@prefapp.es' ]  // this parameter (and only) is optional
     }
]
```

## Acceptance criteria
- [ ] Only one PR per **NEW** image (idempotent)
- [ ] There are unit tests that cover the new feature
